language: node_js
node_js:
  - "10"
notifications:
  email: false
before_script:
  - npm install -g abaplint
script:
  - abaplint --version
  - abaplint abaplint.json "src/**/*.*"
branches:
  only: 
    - master
